apiVersion: apps/v1
kind: Deployment
metadata:
  name: insuranceapp-deploy
  labels:
    app: insuranceapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insuranceapp
  template:
    metadata:
      labels:
        app: insuranceapp
    spec:
      containers:
      - name: insuranceapp-container
        image: balajiveligaram/insuranceapp
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insuranceapp-np-service
  labels:
    app: insuranceapp
spec:
  selector:
    app: insuranceapp

  type: NodePort
  ports:
  - nodePort: 31032
    port: 8081
    targetPort: 8081
